# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='comunidad/%Y/%m/%d/')),
                ('enlace_fb', models.CharField(max_length=200)),
            ],
        ),
    ]
