# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170328_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('lugar', models.TextField()),
                ('tipo', models.CharField(choices=[('Publicación científica', 'Publicación Científica'), ('Blog', 'Blog')], max_length=30)),
                ('año', models.CharField(max_length=4)),
            ],
        ),
    ]
