# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
