# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170328_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/%Y/%m/%d/')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='logo',
            field=models.ImageField(upload_to='comunidades/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(upload_to='proyectos/%Y/%m/%d/'),
        ),
    ]
