# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='enlace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
