# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-05-18 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_publicacion_enlace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificacion',
            options={'ordering': ['año', 'nombre'], 'verbose_name_plural': 'Certificaciones'},
        ),
    ]
