# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-07-21 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190518_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificacion',
            options={'verbose_name_plural': 'Certificaciones'},
        ),
        migrations.RenameField(
            model_name='certificacion',
            old_name='año',
            new_name='año_inicio_vigencia',
        ),
        migrations.AddField(
            model_name='certificacion',
            name='año_fin_vigencia',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='tipo',
            field=models.CharField(choices=[('Curso', 'Curso'), ('Certificación', 'Certificación'), ('Diplomado', 'Diplomado')], default='Curso', max_length=30),
        ),
    ]
